package src.lexer;

public enum TokenType {
	ADD, SUB, MUL, DIV, LESSTHAN, GREATERTHAN, EQUALS, LESSOREQUAL, GREATEROREQUAL, NOTEQUAL, EQUAL, NOT, ASSIGN,
	IDENTIFIER, KEYWORD, STRING, NUMBER, FLOAT, EOF, O_ROUND_BRACKET, C_ROUND_BRACKET, COLON, DOT, COMMA, COMMENT,
	NEWLINE, TAB, WHITESPACE,

}
//LESSTHAN, MORETHAN, EQUALS, LESSOREQUAL, MOREOREQUAL, NOTEQUAL, EQUAL
// < <=
// > <=
// = ==
// ! !=